name: pypi_upload

on:
  release:
    types: [created]

jobs:
  build:
    name: PyPI Upload
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install latest pip, setuptools, twine + wheel
        run: |
          python -m pip install --upgrade pip setuptools twine wheel

      - name: Build wheels
        run: |
          python setup.py bdist_wheel
          python setup.py sdist

      - name: Upload to PyPI via Twine
        env:
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_TOKEN }}
        run: |
          twine upload --verbose --repository testpypi -u '__token__' dist/*
      - name: Upload wheel as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/*.whl
          asset_content_type: application/x-wheel+zip
