name: Releases

on:
  push:
    tags:
      - "*"

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::Version ${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1.8.6
        with:
          name: ${{ steps.get_version.outputs.VERSION }}
          bodyFile: "CHANGES.md"
          token: ${{ secrets.GITHUB_TOKEN }}
